version: '3.2'

services:
  db:
    image: postgres:14.4
    container_name: google_scrapper_ruby_db
    environment:
      - POSTGRES_DB=google_scrapper_ruby_development
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.7
    container_name: google_scrapper_ruby_redis
    ports:
      - "6379:6379"
